workflows:
  ios-release:
    name: iOS Release Build

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install
      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
