workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/Runner.app
